#!/usr/bin/env bash
# Displays all running processes: USER, STARTED (HH:MM:SS), COMMAND in a hierarchical format

ps -eo user,lstart,command --forest \
    | awk 'NR==1 {print "USER STARTED COMMAND"} 
           NR>1 {printf "%-8s %s %s\n", $1, substr($4,1,8), $5}'
