#!/usr/bin/env bash
# Displays all processes (all users, including those without a TTY) in a user-oriented hierarchical format

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
