#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely and says "I am invincible!!!" on SIGTERM

trap 'echo -e "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
